#!/bin/bash

# Selection menu items goes here
SELECTION="Saal1_native_HD Saal1_native_SD Saal1_translated_HD Saal1_translated_SD Saal2_native_HD Saal2_native_SD Saal2_translated_HD Saal2_translated_SD SaalG_native_HD SaalG_native_SD  SaalG_translated_HD SaalG_translated_SD Saal6_native_HD  Saal6_native_SD Saal6_translated_HD Saal6_translated_SD ARTE Lounge Ambient Podcast_HD Podcast_SD quit"

select options in $SELECTION; do
 
# here using the if statements you can perform the required operation

#Saal 1
if [ "$options" = "Saal1_native_HD" ]; then
    mplayer "http://cdn.c3voc.de/s1_native_hd.webm" -title Saal1_native_HD

elif [ "$options" = "Saal1_native_SD" ]; then
    mplayer "http://cdn.c3voc.de/s1_native_sd.webm" -title Saal1_native_SD

elif [ "$options" = "Saal1_translated_HD" ]; then 
    mplayer "http://cdn.c3voc.de/s1_translated_hd.webm" -title Saal1_translated_HD

elif [ "$options" = "Saal1_translated_SD" ]; then 
    mplayer "http://cdn.c3voc.de/s1_translated_sd.webm" -title Saal1_translated_SD


#Saal 2
elif [ "$options" = "Saal2_native_HD" ]; then
        mplayer "http://cdn.c3voc.de/s2_native_hd.webm" -title Saal2_native_HD

elif [ "$options" = "Saal2_native_SD" ]; then
        mplayer "http://cdn.c3voc.de/s2_native_sd.webm" -title Saal2_native_SD

elif [ "$options" = "Saal2_translated_HD" ];then
        mplayer "http://cdn.c3voc.de/s2_translated_hd.webm" -title Saal2_translated_HD

elif [ "$options" = "Saal2_translated_SD" ];then
        mplayer "http://cdn.c3voc.de/s2_translated_sd.webm" -title Saal2_translated_SD

#Saal G        
elif [ "$options" = "SaalG_native_HD" ]; then
        mplayer "http://cdn.c3voc.de/s3_native_hd.webm" -title SaalG_native_HD

elif [ "$options" = "SaalG_native_SD" ]; then
        mplayer "http://cdn.c3voc.de/s3_native_sd.webm" -title SaalG_native_SD

elif [ "$options" = "SaalG_translated_HD" ]; then
        mplayer "http://cdn.c3voc.de/s3_translated_hd.webm" -title SaalG_translated_HD

elif [ "$options" = "SaalG_translated_SD" ]; then
        mplayer "http://cdn.c3voc.de/s3_translated_sd.webm" -title SaalG_translated_SD

#Saal 6        
elif [ "$options" = "Saal6_native_HD" ]; then
        mplayer "http://cdn.c3voc.de/s4_native_hd.webm" -title Saal6_native_HD

elif [ "$options" = "Saal6_native_SD" ]; then
        mplayer "http://cdn.c3voc.de/s4_native_sd.webm" -title Saal6_native_SD
        
elif [ "$options" = "Saal6_translated_HD" ]; then
        mplayer "http://cdn.c3voc.de/s4_translated_hd.webm" -title Saal6_translated_HD

elif [ "$options" = "Saal6_translated_SD" ]; then
        mplayer "http://cdn.c3voc.de/s4_translated_sd.webm" -title Saal6_translated_SD
#ARTE        
elif [ "$options" = "ARTE" ]; then
    rtmpdump -v -r "rtmp://artestras.fc.llnwd.net/artestras" -a "artestras" -f "LNX 11,0,1,98" -W "http://www.arte.tv/flash/mediaplayer/mediaplayer.swf" -p "http://videos.arte.tv/de/videos/html/index-4268756.html" -y "s_artestras_scst_geoFRDE_de?s=1320220800&h=878865258ebb8eaa437b99c3c7598998" --live | mplayer - -title ARTE

#Lounge    
elif [ "$options" = "Lounge" ]; then
        mplayer "http://cdn.c3voc.de" -title Lounge

elif [ "$options"= "Ambient" ]; then
        mplayer "http://cdn.c3voc.de/ambient" -title Ambient
# Podcast
elif [ "$options" = "Podcast_HD" ]; then
        mplayer "http://cdn.c3voc.de/s5_native_hd.webm" -title Podcast_HD

elif [ "$options" = "Podcast_SD" ]; then
        mplayer "http://cdn.c3voc.de/s5_native_sd.webm" -title Podcast_SD

# Ende  
elif [ "$options" = "quit" ]; then
        echo "You have selected $options"
    exit

# if something else is selected, show the menu again
else
    clear;
    echo "please select some options"

fi
done
